### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MatthiasL-SAP** [SAP-samples/frun-csa-policies-best-practices#14]
Is #this depecrated
https://github.com/SAP-samples/frun-csa-policies-best-practices/tree/main/MiscPolicies/ABAPSPStackAge
and replaced by
https://github.com/SAP-samples/frun-csa-policies-best-practices/tree/main/MiscPolicies/FRUN3.0%20FP01%20AgeOfComponents

**Comment by ManfredAch** [comment]
Yes. 
Starting with FRUN 3.0 FP01 please use the policy  Age of component level 3.0 FP01.xml
Best regards
Manfred
