### ISSUE TITLE
Does this rule work correctly?

### ISSUE THREAD

**Issue by MatthiasL-SAP** [SAP-samples/frun-csa-policies-best-practices#17]
https://github.com/SAP-samples/frun-csa-policies-best-practices/blob/main/BaselinePolicies/SOS/v2.2/JAVA_ALL/BL2_SYSTEM-J.xml#L102

97, 102 and 108 seem to be both compliant and non-compliant with the same rule. Whereas on 92 it seems to be working correctly?

**Comment by ManfredAch** [comment]
in line 104 and 110  a not had been missing.
The other parts seem ok.
I will update the policy right now.
