### ISSUE TITLE
Old policies about KERN_PATCHLEVEL fail if the patch level is greater than 999

### ISSUE THREAD

**Issue by FrankBuchholz** [SAP-samples/frun-csa-policies-best-practices#18]
Some policies show rules like this:
```
    <checkitem desc="kernel version which note 0002671160 recommends" id="0002671160">
      <compliant>NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,3,'0') &gt;= '810'</compliant>
      <noncompliant>NAME = 'KERN_PATCHLEVEL'and lpad(VALUE,3,'0') &lt; '810'</noncompliant>
```

The patch level gets padded with zeros for up to 3 characters and compared alphabetically. An alphabetical value like '1024' is lower than '810' and therefore produces a wrong result.  

Solution: Use padding with 4 characters:
```
    <checkitem desc="kernel version which note 0002671160 recommends" id="0002671160">
      <compliant>NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '0810'</compliant>
      <noncompliant>NAME = 'KERN_PATCHLEVEL'and lpad(VALUE,4,'0') &lt; '0810'</noncompliant>
```

Affected files:
```
ABAP_snotes_patchday_2018-01_12.xml
ABAP_snotes_patchday_2018-07.xml
ABAP_snotes_patchday_2018-08.xml
ABAP_snotes_patchday_2019-02.xml
ABAP_snotes_patchday_2019-03.xml
ABAP_snotes_patchday_2019-04.xml
ABAP_snotes_patchday_2019-06.xml
ABAP_snotes_patchday_2019-07.xml
```

**Comment by FrankBuchholz** [comment]
This branch contain corrected rules:
https://github.com/FrankBuchholz/frun-csa-policies-best-practices/tree/Issue_18

Please keep in mind that old security notes describing software changes should not be important - instead of this you should have already updated the support package level of the system.

**Comment by ManfredAch** [comment]
You are right, but we do not update more than 3 years old policies.
