### ISSUE TITLE
Duplicate field in xml

### ISSUE THREAD

**Issue by HansH111** [SAP-samples/frun-csa-policies-best-practices#20]
in file  BaselinePolicies/SOS/v2.4/ABAP_ALL/1ACRITC_CSTO.xml
the content of the checkitem contains a duplicate field 'not_found'

`<checkitem desc="[p1-CRITICAL] Roles with CHANGE ALL TABLES authorization (S_TABU_NAM)" id="CRITAU-A_c.17.2" not_found="ignore" not_found="positive">`

**Comment by ManfredAch** [comment]
sorry for the late response.
And thank you for the feedback.
I did adjust the policy.
