### ISSUE TITLE
Syntax error in HANA SecNotes 2023-09 v3 line 44

### ISSUE THREAD

**Issue by boe-ms** [SAP-samples/frun-csa-policies-best-practices#22]
There are 2 closing ">" at the end of the line.

https://github.com/SAP-samples/frun-csa-policies-best-practices/blob/3e40760211128cd774549b991d6293a512a0b6cc/NotesPolicies/HANA/HANASecNotes_2023-09.xml#L44

**Comment by ManfredAch** [comment]
fixed some time ago
