### ISSUE TITLE
Wrong desc and id

### ISSUE THREAD

**Issue by boe-ms** [SAP-samples/frun-csa-policies-best-practices#23]
Should be 2023-11 instead of 2023-09 for both desc and id.

https://github.com/SAP-samples/frun-csa-policies-best-practices/blob/3e40760211128cd774549b991d6293a512a0b6cc/NotesPolicies/HANA/HANASecNotes_2023-11.xml#L15

**Comment by ManfredAch** [comment]
sorry for late responce.
The policy is adjusted now.
