### ISSUE TITLE
Wrong and/or

### ISSUE THREAD

**Issue by MatthiasL-SAP** [SAP-samples/frun-csa-policies-best-practices#26]
https://github.com/SAP-samples/frun-csa-policies-best-practices/blame/7eaf09a2495326c29790f169aba72945e4453689/BaselinePolicies/SOS/v2.4/ABAP_ALL/2AUSRCTR.xml#L26C6-L26C114

The compliant is OR and the non-compliant is reverse identical but AND. This is faulty.

**Comment by ManfredAch** [comment]
should be fine
NOT needs the and in braket
