### ISSUE TITLE
Compliant vs non-compliant

### ISSUE THREAD

**Issue by MatthiasL-SAP** [SAP-samples/frun-csa-policies-best-practices#27]
https://github.com/SAP-samples/frun-csa-policies-best-practices/blame/7eaf09a2495326c29790f169aba72945e4453689/BaselinePolicies/SOS/v2.4/ABAP_ALL/2ANETENC.xml#L96

I might be misinterpreting this but isn't the compliant identical to the non-compliant?

**Comment by ManfredAch** [comment]
this check uses the operator="NOT_EXIST"
Found: non compliant
Not found: compliant
