### ISSUE TITLE
BL_S-1 ABAP Profile Parameters in General Error

### ISSUE THREAD

**Issue by WorldbreakrSAP** [SAP-samples/frun-csa-policies-best-practices#4]
Hello!

We use your great policies for Focused Run Security Checks and all seems to work fine except the above mentioned check:

We get:
X_COF_EXCEPTION 039: Error in SQL generator: SQL_CODE=339 invalid number: [6930] exception 70006930: attribute value is not a number;exception 70006930: attribute value is not a number

Note 2984454 seems relevant but i can´t find out the exact issue with the generated SQL Statement...

Please can you help us?

Thanks in advance, Christopher Schillerwein-Kral

**Comment by ManfredAch** [comment]
Hello Christopher,
sorry for the late response. I have update the BL_S-1 policy to avoid the SQL error situation.
Additionally I recommend to use the BL22 policies instead: These are available in the folder v2.2
best regards
Manfred
SAP SE

**Comment by WorldbreakrSAP** [comment]
Hello Manfred!

Thanks for the repair! I´m using all of the policies currently, but the one mentioned was the only one that sometimes had an issue.

Great work and thanks for providing the policies to the community and updating them on a regular basis (sec notes).

All the best, Christopher
