### ISSUE TITLE
February 2022 note 0003123427  not included

### ISSUE THREAD

**Issue by MatthiasL-SAP** [SAP-samples/frun-csa-policies-best-practices#6]
I'm looking at the [security note list](https://github.com/SAP-samples/frun-csa-policies-best-practices/blob/main/NotesPolicies/ABAP/ABAP_snotes_patchday_2022/ABAP_snotes_patchday_2022-02.xml) for February 2022 and curious as to why note [0003123427](https://launchpad.support.sap.com/#/notes/3123427)  is not included. It's eerily similar to  [3123396](https://launchpad.support.sap.com/#/notes/3123396) after all, both of them are in essence simply checks of the Kernel. 

Heck, you could probably exclude the latter if you included the first (seeing the kernel versions appear to trump each other) but it would be nice if you could easily check the entire list of security notes from that month and check if they're mitigated.

**Comment by MatthiasL-SAP** [comment]
I did a quick replace all and don't think it should be too much work seeing the similiary in notes, I essentially changed:
- The title
- Replace all on the notes and CVSS score
- Removed all the higher, unrelevant Kernel versions (> 7.53) 
- Checked the SP/patch levels (only difference was 7.53)

`
   <configstore name="SAP_KERNEL">
    <checkitem desc="[p2-CVSS 8.1] Kernel version which note 0003123427 recommends" id="0003123427">
      <compliant>NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '1115'</compliant>
      <noncompliant>NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '1115'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>NAME = 'KERN_REL' and VALUE = '722_REL'</joincompliant>
        <joinnoncompliant>NAME = 'KERN_REL' and VALUE = '722_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
    <checkitem desc="[p2-CVSS 8.1] Kernel version which note 0003123427 recommends" id="0003123427">
      <compliant>NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '1036'</compliant>
      <noncompliant>NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '1036'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>NAME = 'KERN_REL' and VALUE = '749_REL'</joincompliant>
        <joinnoncompliant>NAME = 'KERN_REL' and VALUE = '749_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
    <checkitem desc="[p2-CVSS 8.1] Kernel version which note 0003123427 recommends" id="0003123427">
      <compliant>NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '0914'</compliant>
      <noncompliant>NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '0914'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>NAME = 'KERN_REL' and VALUE = '753_REL'</joincompliant>
        <joinnoncompliant>NAME = 'KERN_REL' and VALUE = '753_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
  </configstore>`

**Comment by ManfredAch** [comment]
Hello Matthias,
the note 3123427 is related to SAP NetWeaver Application Server Java.
We do only publish policies for ABAP notes.
Manfred

**Comment by MatthiasL-SAP** [comment]
Hi @ManfredAch, but that other note from which I copied it from is also not ABAP..
