### ISSUE TITLE
SAP Security Baseline v2.3.

### ISSUE THREAD

**Issue by RLupica** [SAP-samples/frun-csa-policies-best-practices#8]
Hello,
at following URL:
https://github.com/SAP-samples/frun-csa-policies-best-practices/tree/main/BaselinePolicies/SOS

we found the SOS (xml) files for SAP Security Baseline, unfortunately we can't see the ones for latest version (v 2.3 released on November 2021).

Are you going to publish the v2.3 files as well?

Thanks in advance for your support,
Robert Lupica.

**Comment by ManfredAch** [comment]
Hello,
currently we do not have plans to publish policies for v2.3
as there are no major changes coming with v2.3.
Manfred

**Comment by ManfredAch** [comment]
.
